### ISSUE TITLE
Farmbot-Web-API的開發測試資訊

### ISSUE THREAD

**Issue by y12studio** [FBTUG/DevZone#1]
你好

這裡是否適合放入Farmbot-Web-API的開發與測試紀錄 ? 直接PR還是另有適合專案可放 ?

FarmBot/Farmbot-Web-API: Setup, customize, and control FarmBot from any device 

https://github.com/FarmBot/Farmbot-Web-API

**Comment by wuulong** [comment]
y12studio，

如果已經確認是個FBTUG 新專案，或是有明確目標要形成專案，溝通過之後，我會開一個 Repository,如果是還不很確認的話，在這裡直接 Poll Request 進來就可以。

一般只要 Poll Request 進來比較有貢獻的夥伴，就會邀請成為 member
感謝您！

哈爸 https://www.facebook.com/wuulong.hsu
